# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_account_response import CreateAccountResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateAccountResponse(unittest.TestCase):
    """CreateAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAccountResponse(self):
        """Test CreateAccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_account_response.CreateAccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
