# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.suppliers_api import SuppliersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSuppliersApi(unittest.TestCase):
    """SuppliersApi unit test stubs"""

    def setUp(self):
        self.api = SuppliersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_supplier(self):
        """Test case for create_supplier

        Create supplier  # noqa: E501
        """
        pass

    def test_download_supplier_attachment(self):
        """Test case for download_supplier_attachment

        Download supplier attachment  # noqa: E501
        """
        pass

    def test_get_create_update_suppliers_model(self):
        """Test case for get_create_update_suppliers_model

        Get create/update supplier model  # noqa: E501
        """
        pass

    def test_get_supplier(self):
        """Test case for get_supplier

        Get supplier  # noqa: E501
        """
        pass

    def test_get_supplier_attachment(self):
        """Test case for get_supplier_attachment

        Get supplier attachment  # noqa: E501
        """
        pass

    def test_list_supplier_attachments(self):
        """Test case for list_supplier_attachments

        List supplier attachments  # noqa: E501
        """
        pass

    def test_list_suppliers(self):
        """Test case for list_suppliers

        List suppliers  # noqa: E501
        """
        pass

    def test_update_supplier(self):
        """Test case for update_supplier

        Update supplier  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
