# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.direct_incomes_api import DirectIncomesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDirectIncomesApi(unittest.TestCase):
    """DirectIncomesApi unit test stubs"""

    def setUp(self):
        self.api = DirectIncomesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_direct_income(self):
        """Test case for create_direct_income

        Create direct income  # noqa: E501
        """
        pass

    def test_download_direct_income_attachment(self):
        """Test case for download_direct_income_attachment

        Download direct income attachment  # noqa: E501
        """
        pass

    def test_get_create_direct_incomes_model(self):
        """Test case for get_create_direct_incomes_model

        Get create direct income model  # noqa: E501
        """
        pass

    def test_get_direct_income(self):
        """Test case for get_direct_income

        Get direct income  # noqa: E501
        """
        pass

    def test_get_direct_income_attachment(self):
        """Test case for get_direct_income_attachment

        Get direct income attachment  # noqa: E501
        """
        pass

    def test_list_direct_income_attachments(self):
        """Test case for list_direct_income_attachments

        List direct income attachments  # noqa: E501
        """
        pass

    def test_list_direct_incomes(self):
        """Test case for list_direct_incomes

        List direct incomes  # noqa: E501
        """
        pass

    def test_upload_direct_income_attachment(self):
        """Test case for upload_direct_income_attachment

        Create direct income attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
