# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customers_api import CustomersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer(self):
        """Test case for create_customer

        Create customer  # noqa: E501
        """
        pass

    def test_download_customer_attachment(self):
        """Test case for download_customer_attachment

        Download customer attachment  # noqa: E501
        """
        pass

    def test_get_create_update_customers_model(self):
        """Test case for get_create_update_customers_model

        Get create/update customer model  # noqa: E501
        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Get customer  # noqa: E501
        """
        pass

    def test_get_customer_attachment(self):
        """Test case for get_customer_attachment

        Get customer attachment  # noqa: E501
        """
        pass

    def test_list_customer_attachments(self):
        """Test case for list_customer_attachments

        List customer attachments  # noqa: E501
        """
        pass

    def test_list_customers(self):
        """Test case for list_customers

        List customers  # noqa: E501
        """
        pass

    def test_update_customer(self):
        """Test case for update_customer

        Update customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
