# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invoices_api import InvoicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self):
        self.api = InvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_invoice(self):
        """Test case for create_invoice

        Create invoice  # noqa: E501
        """
        pass

    def test_delete_invoice(self):
        """Test case for delete_invoice

        Delete invoice  # noqa: E501
        """
        pass

    def test_download_invoice_pdf(self):
        """Test case for download_invoice_pdf

        Get invoice as PDF  # noqa: E501
        """
        pass

    def test_download_invoices_attachment(self):
        """Test case for download_invoices_attachment

        Download invoice attachment  # noqa: E501
        """
        pass

    def test_get_create_update_invoices_model(self):
        """Test case for get_create_update_invoices_model

        Get create/update invoice model  # noqa: E501
        """
        pass

    def test_get_invoice(self):
        """Test case for get_invoice

        Get invoice  # noqa: E501
        """
        pass

    def test_get_invoice_attachment(self):
        """Test case for get_invoice_attachment

        Get invoice attachment  # noqa: E501
        """
        pass

    def test_list_invoice_attachments(self):
        """Test case for list_invoice_attachments

        List invoice attachments  # noqa: E501
        """
        pass

    def test_list_invoices(self):
        """Test case for list_invoices

        List invoices  # noqa: E501
        """
        pass

    def test_update_invoice(self):
        """Test case for update_invoice

        Update invoice  # noqa: E501
        """
        pass

    def test_upload_invoice_attachment(self):
        """Test case for upload_invoice_attachment

        Push invoice attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
