# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credit_notes_api import CreditNotesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreditNotesApi(unittest.TestCase):
    """CreditNotesApi unit test stubs"""

    def setUp(self):
        self.api = CreditNotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_credit_note(self):
        """Test case for create_credit_note

        Create credit note  # noqa: E501
        """
        pass

    def test_get_create_update_credit_notes_model(self):
        """Test case for get_create_update_credit_notes_model

        Get create/update credit note model  # noqa: E501
        """
        pass

    def test_get_credit_note(self):
        """Test case for get_credit_note

        Get credit note  # noqa: E501
        """
        pass

    def test_list_credit_notes(self):
        """Test case for list_credit_notes

        List credit notes  # noqa: E501
        """
        pass

    def test_update_credit_note(self):
        """Test case for update_credit_note

        Update creditNote  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
