# coding: utf-8

"""
    Accounting API

    A flexible API for pulling accounting data, normalized and aggregated from 20 accounting integrations.  Standardize how you connect to your customers’ accounting software. View, create, update, and delete data in the same way for all the leading accounting platforms.  [Read more...](https://docs.codat.io/accounting-api/overview)  [See our OpenAPI spec](https://github.com/codatio/oas)      # noqa: E501

    OpenAPI spec version: 2.1.0
    Contact: support@codat.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bills_api import BillsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBillsApi(unittest.TestCase):
    """BillsApi unit test stubs"""

    def setUp(self):
        self.api = BillsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bill(self):
        """Test case for create_bill

        Create bill  # noqa: E501
        """
        pass

    def test_delete_bill(self):
        """Test case for delete_bill

        Delete bill  # noqa: E501
        """
        pass

    def test_download_bill_attachment(self):
        """Test case for download_bill_attachment

        Download bill attachment  # noqa: E501
        """
        pass

    def test_get_bill(self):
        """Test case for get_bill

        Get bill  # noqa: E501
        """
        pass

    def test_get_bill_attachment(self):
        """Test case for get_bill_attachment

        Get bill attachment  # noqa: E501
        """
        pass

    def test_get_create_update_bills_model(self):
        """Test case for get_create_update_bills_model

        Get create/update bill model  # noqa: E501
        """
        pass

    def test_list_bill_attachments(self):
        """Test case for list_bill_attachments

        List bill attachments  # noqa: E501
        """
        pass

    def test_list_bills(self):
        """Test case for list_bills

        List bills  # noqa: E501
        """
        pass

    def test_update_bill(self):
        """Test case for update_bill

        Update bill  # noqa: E501
        """
        pass

    def test_upload_bill_attachment(self):
        """Test case for upload_bill_attachment

        Upload bill attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
